### ISSUE TITLE
DM icons where there is no content

### ISSUE THREAD

**Issue by karmatosed** [Automattic/customize-direct-manipulation#1]
I noticed in Publication, that the DM icons have gone a bit overly keen. They are indicating where menus and sidebars could be, however it's really hard to not think it's for the custom header. There is no custom header, it's just using a featured image.

<img width="604" alt="2016-04-22 at 16 55" src="https://cloud.githubusercontent.com/assets/253067/14747324/7c566f04-08ab-11e6-83f1-537b1846a589.png">

As you can see it's super confusing to see them all there.

**Comment by ianstewart** [comment]
A related issue …

![image](https://cloud.githubusercontent.com/assets/545779/14998861/8fa39020-114b-11e6-8314-91f8b558cb05.png)

… when I choose to hide my title and tagline the icons should maybe disappear? (Though I do enjoy watching them slide around as I toggle that option.)

**Comment by sirbrillig** [comment]
Steps to reproduce:

1. Switch theme to Publication.
2. Set home page to latest posts.
3. Add featured image to first post.
4. Add menus to two menu locations: Primary Menu, and Social Menu (they can be the same menu)

The icons for the hidden menus appear on the right side of the viewport.

**Comment by sirbrillig** [comment]
#45 fixes sidebar issues, I think. Not the site-title issue, though. Why? Well... it's because we're not using `visibility` to hide it.

Here's how the site title is hidden:

```css
    position: absolute;
    clip: rect(1px 1px 1px 1px);
```

I'll see if I can add detection for that as well. 💩
