### ISSUE TITLE
Add title attributes to icons

### ISSUE THREAD

**Issue by melchoyce** [Automattic/customize-direct-manipulation#10]
> We should add title attributes to icons, so that some idea is given as to what clicking on it will do. This becomes doubly helpful if icons end up incorrectly positioned, or representing elements that aren't being displayed (eg. when header images are supported, but not currently being used).

Suggested by @kwight. Slated for a future iteration.

**Comment by sirbrillig** [comment]
That's a good idea! Just `title` attributes (maybe visible on hover), or some sort of always-visible label? I suppose we can just start with a title attribute.

**Comment by sirbrillig** [comment]
Merged.
