### ISSUE TITLE
Add support for Site Logos

### ISSUE THREAD

**Issue by melchoyce** [Automattic/customize-direct-manipulation#13]
We'd need to support both core site logos, and Jetpack logos.

Suggested by @karmatosed.

**Comment by taggon** [comment]
Hey! I just created a PR for this. If it works, you will see the icon button on the site logo.

![support_for_site_logo](https://cloud.githubusercontent.com/assets/212034/20591601/bfc736e0-b26c-11e6-9de5-0fc17faa2e4a.png)
