### ISSUE TITLE
  Direct Manipulation icons in hidden widget areas cause horizontal scrolling in RTL languages

### ISSUE THREAD

**Issue by alaczek** [Automattic/customize-direct-manipulation#28]
Originally discussed on an internal blog, but starting an issue, since I don't think this has been addressed.

Summary: When you have a theme that hides a widget area behind a toggle (ie. Ryu, Sorbet) and are viewing an RTL language, the edit link for each widget appears -1000px to the left, which causes horizontal scrolling in the Customizer. We agreed to add `.widgets-hidden` class to themes with hidden widget areas, which is now done.

**Comment by taggon** [comment]
Please ignore the previous commit and PR.

**Comment by sirbrillig** [comment]
Merged and deployed

**Comment by sirbrillig** [comment]
@alaczek can you verify that this fixes the issue that you were seeing?

**Comment by alaczek** [comment]
Yep, it's fixed now. I'm not seeing any horizontal scroll bars anymore. Thank you!
