### ISSUE TITLE
Menu icons can be too far offset.

### ISSUE THREAD

**Issue by kwight** [Automattic/customize-direct-manipulation#3]
We should position the menu icon at the first menu item, rather than the full menu markup itself. Example theme is Dyad.

![screen shot 2016-05-02 at 11 05 43 am](https://cloud.githubusercontent.com/assets/349751/14962974/5ef6fae8-1056-11e6-842b-691e3f61ae30.png)

**Comment by taggon** [comment]
Fixed! :)
