### ISSUE TITLE
Position of DM icons in RTL languages

### ISSUE THREAD

**Issue by alaczek** [Automattic/customize-direct-manipulation#35]
While checking in on issue #16, I noticed that DM icons are always positioned to the left, even if a site is using RTL language. I'm thinking it would make more sense if they were positioned to the right in this case. Here's an example of what it looks like right now on a site running on Ryu theme:

![image](https://cloud.githubusercontent.com/assets/4550351/18620293/9177d234-7e52-11e6-9181-44c49b36b4b9.png)

**Comment by taggon** [comment]
The icons will be shown at the right of the target elements.

![screen shot 2016-11-22 at 23 24 10](https://cloud.githubusercontent.com/assets/212034/20527213/d69714ac-b10a-11e6-9ec0-95aad6ebcb3e.png)

**Comment by taggon** [comment]
Merged.
