### ISSUE TITLE
Publication has icons hidden that should not be hidden, and shows those that should be hidden

### ISSUE THREAD

**Issue by kwight** [Automattic/customize-direct-manipulation#5]
The icons for the regular (visible) sidebar are hidden (they have the `-1000px` offset), while the hidden elements behind the hamburger are visible floating on top:

![screen shot 2016-05-19 at 12 42 24 pm](https://cloud.githubusercontent.com/assets/349751/15407340/3010dca0-1dbf-11e6-99a0-359247cd323a.png)

**Comment by melchoyce** [comment]
Same as #1
